create table if not exists products (
  id bigint generated by default as identity primary key,
  num text default '',
  category text not null,
  type text not null check (type in ('pizza','single')),
  pizza_type text check (pizza_type in ('salgada','doce')),
  is_custom boolean default false,
  name text not null,
  description text default '',
  price numeric,
  price_25 numeric,
  price_35 numeric,
  price_30x50 numeric,
  available boolean default true,
  sort_order integer default 0,
  created_at timestamptz default now()
);

alter table products enable row level security;

create policy "public can read available products"
on products for select
using (available = true);

-- DEMONSTRAÇÃO: permite a dashboard alterar os produtos.
-- Não é seguro para produção porque o login pizza/123 é apenas visual.
create policy "demo can insert products" on products for insert with check (true);
create policy "demo can update products" on products for update using (true) with check (true);
create policy "demo can delete products" on products for delete using (true);

insert into products (id,num,category,type,pizza_type,is_custom,name,description,price,price_25,price_35,price_30x50,available,sort_order) values
(1,'01','pizzas-salgadas','pizza','salgada',false,'Calabresa Especial','Molho de tomate, mussarela, calabresa fatiada, cebola, azeitonas e orégano.',null,48,70,115,true,1),
(2,'02','pizzas-salgadas','pizza','salgada',false,'Frango com Catupiry','Molho de tomate, mussarela, frango desfiado e Catupiry.',null,48,70,115,true,2),
(3,'03','pizzas-salgadas','pizza','salgada',false,'Portuguesa','Molho de tomate, mussarela, presunto, ovo, cebola, pimentão, azeitonas e orégano.',null,48,70,115,true,3),
(4,'04','pizzas-salgadas','pizza','salgada',false,'Quatro Queijos','Molho de tomate, mussarela, Catupiry, provolone e parmesão.',null,53,78,125,true,4),
(5,'05','pizzas-salgadas','pizza','salgada',false,'Bacon com Cheddar','Molho de tomate, mussarela, bacon crocante, cheddar e orégano.',null,53,78,125,true,5),
(6,'06','pizzas-salgadas','pizza','salgada',false,'Lombo Canadense','Molho de tomate, mussarela, lombo canadense, milho e Catupiry.',null,53,78,125,true,6),
(7,'07','pizzas-salgadas','pizza','salgada',false,'Strogonoff de Frango','Molho de tomate, mussarela, strogonoff de frango e batata palha.',null,58,85,135,true,7),
(8,'08','pizzas-salgadas','pizza','salgada',false,'Strogonoff de Carne','Molho de tomate, mussarela, strogonoff de carne e batata palha.',null,58,85,135,true,8),
(9,'09','pizzas-salgadas','pizza','salgada',false,'Maná Especial','Molho de tomate, mussarela, frango, calabresa, bacon, milho, cheddar e cebola roxa.',null,58,85,135,true,9),
(10,'10','pizzas-salgadas','pizza','salgada',false,'Costela Barbecue','Molho de tomate, mussarela, costela desfiada, cebola roxa e molho barbecue.',null,62,90,145,true,10),
(99,'★','monte-sua-pizza','pizza','salgada',true,'Monte Sua Pizza Customizada','Monte sua pizza do seu jeito! Escolha até 2 sabores (25cm), 3 sabores (35cm) ou 4 sabores (30x50cm) diretamente no cardápio.',null,60,80,140,true,11),
(11,'01','pizzas-doces','pizza','doce',false,'Chocolate ao Leite','Creme de avelã, chocolate ao leite e raspas de chocolate.',null,55,80,135,true,12),
(12,'02','pizzas-doces','pizza','doce',false,'Morango Supreme','Creme de avelã, chocolate ao leite, morangos frescos e leite em pó.',null,60,85,145,true,13),
(13,'03','pizzas-doces','pizza','doce',false,'Prestígio','Creme de avelã, chocolate ao leite, coco ralado e leite condensado.',null,55,80,135,true,14),
(14,'04','pizzas-doces','pizza','doce',false,'Banoffee','Doce de leite, banana, leite em pó e canela.',null,65,90,155,true,15),
(15,'05','pizzas-doces','pizza','doce',false,'Oreo','Chocolate branco, Oreo triturado e leite em pó.',null,65,90,155,true,16),
(16,'01','xis-artesanais','single',null,false,'X Salada','Hambúrguer artesanal de coxão mole, ovo frito, mussarela, alface, tomate, milho, ervilha, maionese, ketchup.',30,null,null,null,true,17),
(17,'02','xis-artesanais','single',null,false,'X Frango','Filé de frango, ovo frito, mussarela, alface, tomate, milho, ervilha, maionese, ketchup.',32,null,null,null,true,18),
(18,'03','xis-artesanais','single',null,false,'X Calabresa','Hambúrguer artesanal de coxão mole, calabresa fatiada, ovo frito, mussarela, alface, tomate, milho, ervilha, maionese, ketchup.',35,null,null,null,true,19),
(19,'04','xis-artesanais','single',null,false,'X Bacon','Hambúrguer artesanal de coxão mole, bacon, ovo frito, mussarela, alface, tomate, milho, ervilha, maionese, ketchup.',35,null,null,null,true,20),
(20,'05','xis-artesanais','single',null,false,'X Costela','Hambúrguer artesanal de coxão mole, costela desfiada, cheddar cremoso, ovo frito, mussarela, alface, tomate, milho, ervilha, maionese, ketchup.',40,null,null,null,true,21),
(21,'06','xis-artesanais','single',null,false,'X Strogonoff de Frango','Strogonoff de frango, bacon, cheddar cremoso, Catupiry, ovo frito, mussarela, alface, tomate, milho, ervilha, maionese, ketchup.',40,null,null,null,true,22),
(36,'07','xis-artesanais','single',null,false,'X Strogonoff de Carne','Strogonoff de carne, cheddar cremoso, ovo frito, mussarela, batata palha, maionese, ketchup.',40,null,null,null,true,23),
(22,'08','xis-artesanais','single',null,false,'X Tudo','Hambúrguer artesanal de coxão mole, filé de frango, bacon, calabresa, presunto, cheddar cremoso, ovo frito, mussarela, alface, tomate, milho, ervilha, maionese, ketchup e mostarda.',45,null,null,null,true,24),
(23,'09','xis-artesanais','single',null,false,'X Maná Especial','2 hambúrgueres artesanais de coxão mole, bacon crocante, cheddar cremoso, Catupiry, cebola caramelizada, ovo frito, mussarela, batata palha, maionese, ketchup e mostarda.',48,null,null,null,true,25),
(24,'01','xis-calota','single',null,false,'X Calota Salada','Pão de 30cm, hambúrguer artesanal de coxão mole, ovo frito, mussarela, alface, tomate, milho, ervilha, maionese e ketchup.',85,null,null,null,true,26),
(25,'02','xis-calota','single',null,false,'X Calota Frango','Pão de 30cm, filé de frango, ovo frito, mussarela, alface, tomate, milho, ervilha, maionese e ketchup.',85,null,null,null,true,27),
(26,'03','xis-calota','single',null,false,'X Calota Calabresa','Pão de 30cm, hambúrguer artesanal de coxão mole, calabresa fatiada, ovo frito, mussarela, alface, tomate, milho, ervilha, maionese e ketchup.',95,null,null,null,true,28),
(27,'04','xis-calota','single',null,false,'X Calota Bacon','Pão de 30cm, hambúrguer artesanal de coxão mole, bacon, ovo frito, mussarela, alface, tomate, milho, ervilha, maionese e ketchup.',95,null,null,null,true,29),
(28,'05','xis-calota','single',null,false,'X Calota Tudo','Pão de 30cm, hambúrguer artesanal de coxão mole, filé de frango, bacon, calabresa, presunto, ovo frito, mussarela, alface, tomate, milho, ervilha, maionese e ketchup.',110,null,null,null,true,30),
(29,'','porcoes','single',null,false,'Batata Frita 400g','Porção de batata frita crocante (400g).',20,null,null,null,true,31),
(30,'','bebidas','single',null,false,'Coca-Cola 2L','Garrafa de 2 Litros gelada.',15,null,null,null,true,32),
(31,'','bebidas','single',null,false,'Guaraná Antarctica 2L','Garrafa de 2 Litros gelada.',12,null,null,null,true,33),
(32,'','bebidas','single',null,false,'Coca-Cola Lata','Lata 350ml.',5,null,null,null,true,34),
(33,'','bebidas','single',null,false,'Guaraná Antarctica Lata','Lata 350ml.',5,null,null,null,true,35),
(34,'','bebidas','single',null,false,'Água com Gás 500ml','Garrafa 500ml.',3,null,null,null,true,36),
(35,'','bebidas','single',null,false,'Água sem Gás 500ml','Garrafa 500ml.',3,null,null,null,true,37)
on conflict (id) do update set
name=excluded.name, description=excluded.description, category=excluded.category,
type=excluded.type, pizza_type=excluded.pizza_type, is_custom=excluded.is_custom,
price=excluded.price, price_25=excluded.price_25, price_35=excluded.price_35,
price_30x50=excluded.price_30x50, available=excluded.available, sort_order=excluded.sort_order;
